# Site settings
title: "lsf"
description: "gg"
url: ""
version: v0.1.0

# Contact information
email: ""
phone: ""
address: ""

# Social media
social:
  linkedin: ""
  github: ""
  discord: ""


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  datasets:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


